# Candace Savonen Aug 2021
# For info on how to update this file see: https://github.com/marketplace/actions/repo-file-sync-action#%EF%B8%8F-sync-configuration

group:
  # Repositories to receive changes
  repos: |
    jhudsl/Reproducibility_in_Cancer_Informatics_Quizzes
    jhudsl/Adv_Reproducibility_in_Cancer_Informatics_Quizzes
    jhudsl/Documentation_and_Usability_Quizzes
    broadinstitute/dsp-terra-mooc-intro_Quizzes
    jhudsl/Computing_for_Cancer_Informatics_Leanpub
    fhdsl/Choosing_Genomics_Tools_Quizzes
    fhdsl/Ethical_Data_Handling_for_Cancer_Research_Quizzes
    fhdsl/Overleaf_and_LaTeX_for_Scientific_Articles_Quizzes
    fhdsl/AI_for_software_Quizzes
    jhudsl/Informatics_Research_Leadership_Leanpub
#ADD NEW REPO HERE following the format above#
  # Files which should be updated
  files:
    - source: config_automation.yml
      dest: config_automation.yml
    - source: .github/workflows/
      dest: .github/workflows/
      deleteOrphaned: true
      exclude: |
        send-updates.yml
        test-send-updates.yml
        starting-course.yml
    - source: scripts/spell-check.R
      dest: scripts/spell-check.R
    - source: scripts/make_screenshots.R
      dest: scripts/make_screenshots.R

###### TO ADD NEW REPOSITORY USE THIS FORMAT; Feel free to add/drop files that
# you specifically would like synced (or not).
#
#  # Repositories to receive changes
#  repos: |
#    org/repo_name
#  # Files which should be updated
#  files:
#  - .github/workflows/render-leanpub.yml
#  - .github/workflows/sp-check.yml
#  - .github/workflows/url-checker.yml
#  - .github/workflows/ISSUE_TEMPLATES/issue_template.md
#  - .github/workflows/PULL_REQUEST_TEMPLATE.md
#  - scripts/*
#  - getting_started.md
