# Candace Savonen Aug 2021
# For info on how to update this file see: https://github.com/marketplace/actions/repo-file-sync-action#%EF%B8%8F-sync-configuration

group:
  # Repositories to receive changes
  repos: |
    jhudsl/Documentation_and_Usability_Quizzes
    broadinstitute/dsp-terra-mooc-intro_Quizzes
    jhudsl/Computing_for_Cancer_Informatics_Leanpub

#ADD NEW REPO HERE following the format above#
  # Files which should be updated
  files:
  - .github/workflows/render-leanpub.yml
  - .github/workflows/check-quizzes.yml
  - .github/workflows/sp-check.yml
  - .github/workflows/url-checker.yml
  - .github/workflows/release-notes.yml
  - .github/workflows/ISSUE_TEMPLATES/issue_template.md
  - .github/workflows/PULL_REQUEST_TEMPLATE.md
  - scripts/spell-check.R
  - scripts/get_rmd_filenames.R

###### TO ADD NEW REPOSITORY USE THIS FORMAT; Feel free to add/drop files that
# you specifically would like synced (or not).
#
#  # Repositories to receive changes
#  repos: |
#    org/repo_name
#  # Files which should be updated
#  files:
#  - .github/workflows/render-leanpub.yml
#  - .github/workflows/sp-check.yml
#  - .github/workflows/url-checker.yml
#  - .github/workflows/ISSUE_TEMPLATES/issue_template.md
#  - .github/workflows/PULL_REQUEST_TEMPLATE.md
#  - scripts/*
#  - getting_started.md
