# Candace Savonen Aug 2021
# For info on how to update this file see: https://github.com/marketplace/actions/repo-file-sync-action#%EF%B8%8F-sync-configuration

group:
  # Repositories to receive changes
  repos: |
    jhudsl/Reproducibility_in_Cancer_Informatics_Quizzes
    jhudsl/Adv_Reproducibility_in_Cancer_Informatics_Quizzes
    jhudsl/Documentation_and_Usability_Quizzes
    broadinstitute/dsp-terra-mooc-intro_Quizzes
    jhudsl/Computing_for_Cancer_Informatics_Leanpub

#ADD NEW REPO HERE following the format above#
  # Files which should be updated
  files:
    - source: .github/workflows/render-leanpub.yml
      dest: .github/workflows/render-leanpub.yml
    - source: .github/workflows/check-quizzes.yml
      dest: .github/workflows/check-quizzes.yml
    - source: .github/workflows/sp-check.yml
      dest: .github/workflows/sp-check.yml
    - source: .github/workflows/url-checker.yml
      dest: .github/workflows/url-checker.yml
    - source: .github/workflows/release-notes.yml
      dest: .github/workflows/release-notes.yml
    - source: .github/workflows/release-notes.yml
      dest: .github/workflows/release-notes.yml
    - source: .github/workflows/ISSUE_TEMPLATES/issue_template.md
      dest: .github/workflows/ISSUE_TEMPLATES/issue_template.md
    - source: scripts/spell-check.R
      dest: scripts/spell-check.R
    - source: scripts/get_rmd_filenames.R
      dest: scripts/get_rmd_filenames.R
    - source: scripts/make_screenshots.R
      dest: scripts/make_screenshots.R

###### TO ADD NEW REPOSITORY USE THIS FORMAT; Feel free to add/drop files that
# you specifically would like synced (or not).
#
#  # Repositories to receive changes
#  repos: |
#    org/repo_name
#  # Files which should be updated
#  files:
#  - .github/workflows/render-leanpub.yml
#  - .github/workflows/sp-check.yml
#  - .github/workflows/url-checker.yml
#  - .github/workflows/ISSUE_TEMPLATES/issue_template.md
#  - .github/workflows/PULL_REQUEST_TEMPLATE.md
#  - scripts/*
#  - getting_started.md
