name: File reminder issue for Leanpub publishing
on:
  push:
    branches:
      - main
    paths: [ manuscript/* ]
jobs:
  reminder:
    runs-on: ubuntu-latest
    steps:

      - name: Find issue comment
        uses: peter-evans/find-comment@v1
        id: fc
        with:
          comment-author: 'github-actions[bot]'
          body-includes: publish these changes to [Leanpub]

      # If the issue isn't still open, then make a new one
      - name: Publish Leanpub
        if: ${{ steps.fc.outputs.comment-id == 0 }}
        uses: peter-evans/create-issue-from-file@v2.3.2
        with:
          title: Reminder to publish changes to Leanpub
          content-filepath: .github/automatic-issues/publish-leanpub.md
          labels: automated issue
